# Fonts

font_family      SauceCodePro NFM
bold_font        SauceProCode NFM Bold
italic_font      SauceProCode NFM Italic
bold_italic_font SauceProCode NFM Bold Italic

font_size        12.0

# Windows appearance
# hide_window_decorations yes
# linux_display_server x11
